---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: testproj
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: REGISTRY_URL/replace-me-namespace/testproj
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
